baseURL = "https://ymmt-coffee.github.io/my-blog/"
languageCode = "ja"
title = "ブログタイトル（あとで変更OK）"
theme = "PaperMod"
buildFuture = false

[frontmatter]
  date = ["date", "publishDate"]

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
