baseURL = "https://ymmt-coffee.github.io/my-blog/"
languageCode = "ja"
title = "logs"
theme = "PaperMod"
buildFuture = false

[frontmatter]
  date = ["date", "publishDate"]

[params]
  defaultTheme = "auto"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  disableSpecial1stPost = true

  [params.analytics]
    provider = "umami"

    [params.analytics.umami]
      scriptUrl = "https://cloud.umami.is/script.js"
      websiteId = "c0e08380-ff29-4ec6-a9af-282f5b48afc6"

    [params.analytics.google]
      measurementId = ""

    [params.analytics.plausible]
      domain = ""
